### ISSUE TITLE
Feature request: Display routes in map

### ISSUE THREAD

**Issue by vspedr** [hentrymartin/rc-here-maps#3]
Hi, first of all thanks for sharing this module, it looks very promising!

I'd like to display routes in the map and I see you started working on this feature here: 30c6b31
Are you still working on this or have you made any progress after this commit? Maybe we could work together on getting it done.

Here's an [example](https://github.com/heremaps/maps-api-for-javascript-examples/blob/master/map-with-route-from-a-to-b/js/app.js) from their official documentation.

**Comment by hentrymartin** [comment]
Hi @vspedr,

Thanks a lot for using the library. 

I couldn't able to work on this feature due to other works. It would be great if you can work on it and create a PR. 

Thanks,
Hentry.

**Comment by vspedr** [comment]
Sure, I'm working on it and will open a PR as soon as possible. Thanks!
